include(cmake/Variables.cmake)

function(set_compile_flags)
  if ("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
    add_compile_options(${FAST_COMPILE_FLAGS})
  elseif ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    add_compile_options(${DEBUG_COMPILE_FLAGS})
  elseif ("${CMAKE_BUILD_TYPE}" STREQUAL "RelWithDebInfo")
    add_compile_options(${FAST_COMPILE_FLAGS} -ggdb3)
  else()
    message(FATAL_ERROR "Unknown CMAKE_BUILD_TYPE specified")
  endif() 

  get_property(CAN_USE_LLVM_LTO GLOBAL PROPERTY CAN_USE_LLVM_LTO)

  if ("${HCPU_LTO}" STREQUAL "ON" AND "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    add_compile_options(-flto)
    add_link_options(-flto)
    message(STATUS "Enabled LTO")
  elseif("${HCPU_LTO}" STREQUAL "ON" AND "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang" AND "${CAN_USE_LLVM_LTO}" STREQUAL "YES")
    add_compile_options(-flto=thin)
    add_link_options(-flto=thin)
    message(STATUS "Enabled LTO")
  else()
    message(STATUS "LTO wasn't enabled")
  endif()

  string(TOLOWER "${HCPU_MARCH_NATIVE}" HCPU_MARCH_NATIVE)
  if ("${HCPU_MARCH_NATIVE}" STREQUAL "on")
    add_compile_options(-march=native)
    message(STATUS "Enabled -march=native flag")
  endif()

  string(TOLOWER "${HCPU_SANITIZERS}" HCPU_SANITIZERS)
  if (NOT "${HCPU_SANITIZERS}" STREQUAL "off")
    add_compile_options(-fsanitize=address,leak)
    add_link_options(-fsanitize=address,leak)
    message(STATUS "Enabling sanitizers")
  endif()
endfunction()

function(detect_compilers)
  string(TOLOWER "${HCPU_COMPILER}" HCPU_COMPILER)
  string(TOLOWER "${HCPU_LTO}" HCPU_LTO)
  string(SUBSTRING "${CMAKE_C_COMPILER}" 0 1 IS_ABS)
  if ("${HCPU_COMPILER}" STREQUAL "auto" OR "${HCPU_COMPILER}" STREQUAL "")
    message(STATUS "Using CMake compiler autodetection")
  elseif ("${HCPU_COMPILER}" STREQUAL "clang")
    if ("${CMAKE_C_COMPILER}" STREQUAL "" OR "${IS_ABS}" STREQUAL "/")
      message(STATUS "Searching for clang")
      execute_process(COMMAND which clang OUTPUT_VARIABLE CMAKE_C_COMPILER OUTPUT_STRIP_TRAILING_WHITESPACE)
      execute_process(COMMAND which clang++ OUTPUT_VARIABLE CMAKE_CXX_COMPILER OUTPUT_STRIP_TRAILING_WHITESPACE)
      set(CMAKE_C_COMPILER ${CMAKE_C_COMPILER} CACHE INTERNAL "CMAKE_C_COMPILER")
      set(CMAKE_CXX_COMPILER ${CMAKE_CXX_COMPILER} CACHE INTERNAL "CMAKE_CXX_COMPILER")
    elseif (NOT "${IS_ABS}" STREQUAL "/")
      message(STATUS "Searching for ${CMAKE_C_COMPILER}")
      execute_process(COMMAND which ${CMAKE_C_COMPILER} OUTPUT_VARIABLE CMAKE_C_COMPILER OUTPUT_STRIP_TRAILING_WHITESPACE)
      execute_process(COMMAND which ${CMAKE_CXX_COMPILER} OUTPUT_VARIABLE CMAKE_CXX_COMPILER OUTPUT_STRIP_TRAILING_WHITESPACE)
      set(CMAKE_C_COMPILER ${CMAKE_C_COMPILER} CACHE INTERNAL "CMAKE_C_COMPILER")
      set(CMAKE_CXX_COMPILER ${CMAKE_CXX_COMPILER} CACHE INTERNAL "CMAKE_CXX_COMPILER")
    endif()

    find_program(LLD_AVAILABLE "ld.lld")
    if ("${LLD_AVAILABLE}" STREQUAL LLD_AVAILABLE-NOT_FOUND AND "${HCPU_LTO}" STREQUAL "yes")
      message(WARNING "LLD not found: LLVM LTO will be disabled")
      set(CAN_USE_LLVM_LTO "NO" PARENT_SCOPE)
    else()
      execute_process(COMMAND which ld.lld OUTPUT_VARIABLE CMAKE_LINKER OUTPUT_STRIP_TRAILING_WHITESPACE)
      message(STATUS "Found LLD")
      set_property(GLOBAL PROPERTY CAN_USE_LLVM_LTO "YES")
    endif()
  elseif ("${HCPU_COMPILER}" STREQUAL "gcc")
    if ("${CMAKE_C_COMPILER}" STREQUAL "" OR "${IS_ABS}" STREQUAL "/")
      message(STATUS "Searching for gcc")
      execute_process(COMMAND which gcc OUTPUT_VARIABLE CMAKE_C_COMPILER)
      execute_process(COMMAND which g++ OUTPUT_VARIABLE CMAKE_CXX_COMPILER)
    elseif (NOT "${IS_ABS}" STREQUAL "/")
      message(STATUS "Searching for ${CMAKE_C_COMPILER}")
      execute_process(COMMAND which ${CMAKE_C_COMPILER} OUTPUT_VAR
IABLE CMAKE_C_COMPILER)
      execute_process(COMMAND which ${CMAKE_CXX_COMPILER} OUTPUT_VARIABLE CMAKE_CXX_COMPILER)
    endif()
  else()
    message(FATAL_ERROR "HCPU_COMPILER not specified: cannot proceed. Please specify one of: auto, clang, gcc.")
  endif()
endfunction()
