if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  set(FAST_COMPILE_FLAGS "-Wall -Wextra -Werror -Wno-pointer-arith -flto=thin -O3 -Wno-unused-const-variable")
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set(FAST_COMPILE_FLAGS "-Wall -Wextra -Werror -Wno-pointer-arith -flto -O3 -Wno-unused-const-variable")
endif()
set(DEBUG_COMPILE_FLAGS "-Wall -Wextra -Werror -Wno-pointer-arith -O0 -ggdb3 -Wno-unused-const-variable")
set(NOOPT_COMPILE_FLAGS "-Wall -Wextra -Werror -Wno-pointer-arith -O0 -Wno-unused-const-variable")